create database threesept
create table emp2
(
EMPID INT IDENTITY(1,1) NOT NULL,
FIRSTNAME VARCHAR(75) NOT NULL,
LASTNAME VARCHAR(75) NOT NULL,
SALARY DECIMAL(15,2) NOT NULL,
PRIMARY KEY(EMPID)
)
ALTER TABLE emp2 ADD STATUS VARCHAR(10);

ALTER TABLE emp2 ADD DEPATMENTID INT;

INSERT INTO emp2(FIRSTNAME,LASTNAME,SALARY,STATUS) VALUES ('XYZ','PQR',30000,'Active');
INSERT INTO emp2(FIRSTNAME,LASTNAME,SALARY,STATUS) VALUES ('LMN','ABC',50000,'InActive');
INSERT INTO emp2(FIRSTNAME,LASTNAME,SALARY,STATUS,DEPATMENTID) VALUES ('PQR','DTR',40000,'InActive',01);
INSERT INTO emp2 (FIRSTNAME,LASTNAME,SALARY,STATUS,DEPATMENTID) VALUES ('JNL','NHK',70000,'InActive',03);

select * from emp2;
TRUNCATE TABLE emp2;
select * from emp2;
DROP TABLE emp2;
SELECT * from emp2;


CREATE TABLE DEPARTMENT2
(
DEPTID INT PRIMARY KEY,
DEPTNAME VARCHAR(75)NOT NULL,
EMPID INT
)


INSERT INTO DEPARTMENT2 VALUES (1001,'SALES',01);
INSERT INTO DEPARTMENT2 VALUES (1002,'FINANCE',02);
INSERT INTO DEPARTMENT2 VALUES (1003,'INVENTORY',03);

SELECT * FROM DEPARTMENT2;
DROP TABLE DEPARTMENT2;

CREATE TABLE DEPARTMENT3
(
DEPTID INT PRIMARY KEY,
DEPTNAME VARCHAR(75)NOT NULL,
EMPID INT FOREIGN KEY REFERENCES emp2(EMPID)
)


INSERT INTO DEPARTMENT3 VALUES (1001,'SALES',01);
INSERT INTO DEPARTMENT3 VALUES (1002,'FINANCE',02);
INSERT INTO DEPARTMENT3 VALUES (1003,'INVENTORY',03);

DELETE FROM DEPARTMENT3; 

DELETE FROM DEPARTMENT3 WHERE DEPTNAME='INVENTORY';

SELECT * FROM DEPARTMENT3;

DELETE FROM DEPARTMENT3 WHERE DEPTID = (SELECT DEPTID FROM DEPARTMENT3 WHERE DEPTNAME = 'SALES');

CREATE TABLE STUDENT
(
STDID INT PRIMARY KEY,
STDROLLNO INT UNIQUE,
STDNAME VARCHAR(75) NOT NULL,
STDCLASS VARCHAR(10) DEFAULT 'IX',
STDRESULT VARCHAR(10),
CHECK (STDRESULT = 'PASS')
)

INSERT INTO STUDENT(STDID,STDROLLNO,STDNAME,STDRESULT) VALUES (1001,12,'VIVEK','PASS');
INSERT INTO STUDENT(STDID,STDROLLNO,STDNAME,STDRESULT) VALUES (1002,13,'KRUNAL','PASS');
INSERT INTO STUDENT(STDID,STDROLLNO,STDNAME,STDRESULT) VALUES (1004,52,'NIRBHAY','PASS');
INSERT INTO STUDENT(STDID,STDROLLNO,STDNAME,STDRESULT) VALUES (1007,23,'ABHI','PASS');
INSERT INTO STUDENT(STDID,STDROLLNO,STDNAME,STDRESULT) VALUES (1014,42,'SAMEER','PASS');
INSERT INTO STUDENT(STDID,STDROLLNO,STDNAME,STDRESULT) VALUES (1011,62,'NIKHIL','PASS');
SELECT * FROM STUDENT;

CREATE TABLE DEPT
(
DEPTID INT PRIMARY KEY,
DEPTNAME VARCHAR(75) NOT NULL,
SID INT FOREIGN KEY REFERENCES STUDENT(STDID)
)

INSERT INTO DEPT VALUES (10001,'PRIMARY',1001);
INSERT INTO DEPT VALUES (10021,'SECONDARY',1004);
INSERT INTO DEPT VALUES (10101,'HIGHER SECONDARY',1014);
INSERT INTO DEPT VALUES (11001,'JR COLLEGE',1007);
INSERT INTO DEPT VALUES (11011,'JR COLLEGE',1031);
SELECT * FROM DEPT;

CREATE TABLE ADDRES
(
HOUSENO INT,
LOCATOION VARCHAR(75),
VILAGE VARCHAR(75),
CITY VARCHAR(75),
PINCODE INT
)

ALTER TABLE ADDRES ADD UNIQUE(LOCATOION);
ALTER TABLE ADDRES ADD DEFAULT 'PANVEL' FOR CITY;
ALTER TABLE ADDRES ADD CHECK(PINCODE=410206);

ALTER TABLE ADDRES ALTER COLUMN  VILAGE VARCHAR(75) NOT NULL;
